services:
     nextjs-project:
          build:
               context: ./nextjs-project
               dockerfile: Dockerfile
          ports:
               - "3000:3000"
          volumes:
               - ./nextjs-project:/app
               - /app/node_modules
          env_file:
               - .env
          depends_on:
               - mongodb
          networks:
               - devNetwork
          command: ["pnpm", "dev"]

     mongodb:
          image: mongo:latest
          container_name: dev_mc_mongo_db
          ports:
               - "27017:27017"
          environment:
               MONGO_INITDB_ROOT_USERNAME: root
               MONGO_INITDB_ROOT_PASSWORD: 123456
          volumes:
               - ./mangrove_mongodb_data:/data/db
          networks:
               - devNetwork

networks:
     devNetwork:
          driver: bridge
