services:
     mangrove-collection:
          build:
               context: ./nextjs-project
               dockerfile: Dockerfile
          ports: -"3000":"8080"
          volumes:
               - ./nextjs-project:/app
               - /app/node_modules
          env_file:
               - .env
          depends_on:
               - mongodb

networks:
     devNetwork:
          driver: bridge
