export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function UserLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <>{children}</>;
}
