<?php

namespace App\Support;

/**
 * The curated category icon library (Lucide outlines), generated by
 * `node scripts/build-category-icons.mjs` into resources/data/category-icons.json.
 *
 * Each icon: { name, label, group, keywords: string[], nodes: [tag, attrs][] }.
 */
final class CategoryIcons
{
    /** @var array<string, array{name: string, label: string, group: string, keywords: list<string>, nodes: list<array{0: string, 1: array<string, string>}>}>|null */
    private static ?array $icons = null;

    /**
     * @return list<array{name: string, label: string, group: string, keywords: list<string>, nodes: list<array{0: string, 1: array<string, string>}>}>
     */
    public static function all(): array
    {
        return array_values(self::byName());
    }

    /**
     * @return list<string>
     */
    public static function names(): array
    {
        return array_keys(self::byName());
    }

    /**
     * @return array{name: string, label: string, group: string, keywords: list<string>, nodes: list<array{0: string, 1: array<string, string>}>}|null
     */
    public static function find(?string $name): ?array
    {
        return $name === null ? null : (self::byName()[$name] ?? null);
    }

    private static function byName(): array
    {
        if (self::$icons === null) {
            $icons = json_decode((string) file_get_contents(resource_path('data/category-icons.json')), true, flags: JSON_THROW_ON_ERROR);
            self::$icons = array_column($icons, null, 'name');
        }

        return self::$icons;
    }
}
